{
 "title": "LoRa",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"temp\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"hum\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"pres\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Sequence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"seq\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Temperature fluctuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"temp\")\r\n  |> toFloat()  // ensure float type\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity Fluctuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"hum\")\r\n  |> toFloat()  // ensure float type\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Pressure Fluctuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "query": "from(bucket: \"lora\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lora_rx\" and r.device == \"heltec-v3-1\" and r._field == \"pres\")\r\n  |> toFloat()  // ensure float type\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  }
 ]
}